# rebuild when changing python code or requirements
FROM stepbot-os:latest

ENV VIRTUAL_ENV=/bot/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /bot
COPY . .
ENTRYPOINT ["/bot/venv/bin/python", "src/main.py"]
