# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "PyNaCl" = super.buildPythonPackage rec {
    pname = "PyNaCl";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a7/22/27582568be639dfe22ddb3902225f91f2f17ceff88ce80e4db396c8986da/PyNaCl-1.5.0.tar.gz";
      sha256 = "1fi0jbxhh3svajzldlb6gj5sr5a48v11xlmx0wb831db167l9iwa";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "PyYAML" = super.buildPythonPackage rec {
    pname = "PyYAML";
    version = "6.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5ce7be1eda0/PyYAML-6.0.1.tar.gz";
      sha256 = "0hsa7g6ddynifrwdgadqcx80khhblfy94slzpbr7birn2w5ldpxz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "aiohttp" = super.buildPythonPackage rec {
    pname = "aiohttp";
    version = "3.7.4.post0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/99/f5/90ede947a3ce2d6de1614799f5fea4e93c19b6520a59dc5d2f64123b032f/aiohttp-3.7.4.post0.tar.gz";
      sha256 = "1kzyg94qi264rpzxs4a9x2lg3amvrz6yl6cqdg3agxg5xfck4ga9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."async-timeout"
      self."attrs"
      self."chardet"
      self."multidict"
      self."typing-extensions"
      self."yarl"
    ];
  };
  "aiosignal" = super.buildPythonPackage rec {
    pname = "aiosignal";
    version = "1.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/3b/87/fe94898f2d44a93a35d5aa74671ed28094d80753a1113d68b799fab6dc22/aiosignal-1.2.0-py3-none-any.whl";
      sha256 = "0fjfsrsspwlg2cjbj33dw5gx1kqd3zwldmkadvgq3lbc0c4j3ri6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."frozenlist"
    ];
  };
  "async-timeout" = super.buildPythonPackage rec {
    pname = "async-timeout";
    version = "3.0.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl";
      sha256 = "18wy5w0wk37ikx9n5yc8s9746bgqz3wdddbc1d6jfz98glcwm4a2";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "21.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/be/7abce643bfdf8ca01c48afa2ddf8308c2308b0c3b239a44e57d020afa0ef/attrs-21.4.0-py2.py3-none-any.whl";
      sha256 = "1d185347kgm169c8fs1i8rmcvv65hx4fj7w5mcv5smks9mwf69rd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "bcrypt" = super.buildPythonPackage rec {
    pname = "bcrypt";
    version = "3.2.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/e8/36/edc85ab295ceff724506252b774155eff8a238f13730c8b13badd33ef866/bcrypt-3.2.2.tar.gz";
      sha256 = "1yvbdfmkssx1jf2lrhbs58xljmyi3p82r7rav82pf1bp44642g23";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "certifi" = super.buildPythonPackage rec {
    pname = "certifi";
    version = "2020.6.20";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl";
      sha256 = "0hgw963hnmp907cpbsv81x19zn84xywzzkjcnfyibfih3ygq3h4g";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cffi" = super.buildPythonPackage rec {
    pname = "cffi";
    version = "1.15.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/2b/a8/050ab4f0c3d4c1b8aaa805f70e26e84d0e27004907c5b8ecc1d31815f92a/cffi-1.15.1.tar.gz";
      sha256 = "1y9lr651svbzf1m03s4lqbnbv2byx8f6f0ml7hjm24vvlfwvy06l";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pycparser"
    ];
  };
  "chardet" = super.buildPythonPackage rec {
    pname = "chardet";
    version = "4.0.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl";
      sha256 = "198xs99vbvcj312d1bk7bgn7aix5h64sqi3hwvr1i4gxcr6har7q";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "charset-normalizer" = super.buildPythonPackage rec {
    pname = "charset-normalizer";
    version = "2.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/94/69/64b11e8c2fb21f08634468caef885112e682b0ebe2908e74d3616eb1c113/charset_normalizer-2.1.0-py3-none-any.whl";
      sha256 = "19gq6mx3qhvqx695mvw86xnv8idwl3chhsjvyckp95815grbd2ai";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "colorzero" = super.buildPythonPackage rec {
    pname = "colorzero";
    version = "1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/cc/a2/718e78485d0a42c3c2971e0d4a0eb9878bd1121cd640f0773de0695c858e/colorzero-1.1-py2.py3-none-any.whl";
      sha256 = "18x04qm639lp0qnk79fh3saarzrz4jysam7zfwpjpplkn8anvhz3";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "cryptography" = super.buildPythonPackage rec {
    pname = "cryptography";
    version = "37.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/51/05/bb2b681f6a77276fc423d04187c39dafdb65b799c8d87b62ca82659f9ead/cryptography-37.0.2.tar.gz";
      sha256 = "13n6nmagsrj025w2ybva75bzlgi6s83p01s9ixbagkn97hjss97j";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."cffi"
    ];
  };
  "discord.py" = super.buildPythonPackage rec {
    pname = "discord.py";
    version = "2.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/9c/7e/5f1b24b2ced0c4b3042204f7827b57c7dcb26d368e9b0fde8cec7853cf30/discord.py-2.3.2-py3-none-any.whl";
      sha256 = "19k0b7n2a9gwzjxq70ijaw73wrlqr46p1142715wc46bqfgng94x";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."aiohttp"
    ];
  };
  "distro" = super.buildPythonPackage rec {
    pname = "distro";
    version = "1.5.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/25/b7/b3c4270a11414cb22c6352ebc7a83aaa3712043be29daa05018fd5a5c956/distro-1.5.0-py2.py3-none-any.whl";
      sha256 = "1697rn1mwvyrqgcr4wyi5i1qc1789995hhk2vb8113g1cgbywx6z";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ffmpeg" = super.buildPythonPackage rec {
    pname = "ffmpeg";
    version = "1.4";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f0/cc/3b7408b8ecf7c1d20ad480c3eaed7619857bf1054b690226e906fdf14258/ffmpeg-1.4.tar.gz";
      sha256 = "1fdml3drkwcppgwwgpb01k55v0a7jwcc4cw4jcwivwhgi4n6jcb9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "frozenlist" = super.buildPythonPackage rec {
    pname = "frozenlist";
    version = "1.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/8c/1f/49c96ccc87127682ba900b092863ef7c20302a2144b3185412a08480ca22/frozenlist-1.4.0.tar.gz";
      sha256 = "0l92qbyqp40lzi5dbyvivim80cvdgj49zcgd8904a1r91ggkn5h9";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "idna" = super.buildPythonPackage rec {
    pname = "idna";
    version = "2.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl";
      sha256 = "1h280sli58v5dapmf79rnnqdrrk0xjn8vi3pxppknllv3r5q0zdr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "jsonschema" = super.buildPythonPackage rec {
    pname = "jsonschema";
    version = "3.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl";
      sha256 = "0qyidiicwn27ya7r4q7cjbra8gna5vkwnfg1kkp7nmvg47w3qnsf";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."attrs"
      self."pyrsistent"
      self."setuptools"
      self."six"
    ];
  };
  "mongoengine" = super.buildPythonPackage rec {
    pname = "mongoengine";
    version = "0.24.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f8/70/b8446e7c3bba35b363edfb79a60b97b1b5d6076528ac1d5065e9d753e994/mongoengine-0.24.1-py3-none-any.whl";
      sha256 = "1b2gshfhib92wqkm0lj6bzdiq5l0l6022d54rgmisxdkpijqp1v8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."pymongo"
    ];
  };
  "multidict" = super.buildPythonPackage rec {
    pname = "multidict";
    version = "6.0.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fa/a7/71c253cdb8a1528802bac7503bf82fe674367e4055b09c28846fdfa4ab90/multidict-6.0.2.tar.gz";
      sha256 = "04xhddyvb725w62f6az29hf842s39mxdzwkhykql6k4fydsvvwsz";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "paramiko" = super.buildPythonPackage rec {
    pname = "paramiko";
    version = "2.11.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/04/e5/39ec73dd4a8769d6759b8d6c60a1b2c9337f585407c2ae8bfb8ccb734278/paramiko-2.11.0-py2.py3-none-any.whl";
      sha256 = "0w62f9ml4lxn3x6pgffnz0fmhdnn06hwxprkp5vk4xmgigf2apv5";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyNaCl"
      self."bcrypt"
      self."cryptography"
      self."six"
    ];
  };
  "pathspec" = super.buildPythonPackage rec {
    pname = "pathspec";
    version = "0.11.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b4/2a/9b1be29146139ef459188f5e420a66e835dda921208db600b7037093891f/pathspec-0.11.2-py3-none-any.whl";
      sha256 = "081ax48nr6ajmbsv1464nxjbnnx91ram263bp7ppkrh5mwrx4vhx";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "praw" = super.buildPythonPackage rec {
    pname = "praw";
    version = "7.7.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b3/93/55ae62910b94b46ecdd0ee8765289304f8df8deeaa1df7a96b0831c637ff/praw-7.7.0-py3-none-any.whl";
      sha256 = "03j2nl6zwijj6gp3gh0ynr3pg4964b7kchbmn1d3lwq6615mq592";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."prawcore"
      self."update-checker"
      self."websocket-client"
    ];
  };
  "prawcore" = super.buildPythonPackage rec {
    pname = "prawcore";
    version = "2.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d6/36/55cc2cab22aafbebd52ddac4ccb670b920b54eb6ddbdb8573c79ca870d8a/prawcore-2.3.0-py3-none-any.whl";
      sha256 = "1xggrkxrby0xbb03d9ys11vl6c9h8hgj08p7lcya21ps8ys7vha8";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
    ];
  };
  "pycparser" = super.buildPythonPackage rec {
    pname = "pycparser";
    version = "2.21";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl";
      sha256 = "1agwca0hgbpwmr9snhxafqjhfd52mq083rw5n7vf25amallm9r4f";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pymongo" = super.buildPythonPackage rec {
    pname = "pymongo";
    version = "4.1.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/19/5c/ef2753159dfb4e5879e2b091412186f66faae01ce8151761617138c28c91/pymongo-4.1.1.tar.gz";
      sha256 = "1m9hc2a4kgg10xy3g5x00z4a7rrk9s0rbf5qfypwnhq0kdfg5f6p";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "pyrsistent" = super.buildPythonPackage rec {
    pname = "pyrsistent";
    version = "0.18.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/42/ac/455fdc7294acc4d4154b904e80d964cc9aae75b087bbf486be04df9f2abd/pyrsistent-0.18.1.tar.gz";
      sha256 = "15pb8ry525h9z1670kzqi5915y004yjsrwsdf6x5awisk65izmnl";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "python-dotenv" = super.buildPythonPackage rec {
    pname = "python-dotenv";
    version = "0.20.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/30/5f/2e5c564bd86349fe6b82ca840f46acf6f4bb76d79ba9057fce3d3e008864/python_dotenv-0.20.0-py3-none-any.whl";
      sha256 = "0f19m57wwh0sjfzsn95p28xfcyqf4196snv7zpj85r0zwrxihanr";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "requests" = super.buildPythonPackage rec {
    pname = "requests";
    version = "2.25.1";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl";
      sha256 = "07l7fm7y9zkvmpfli803dni6iwyyhy1f804y46wycam46r70h462";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."certifi"
      self."chardet"
      self."idna"
      self."urllib3"
    ];
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.16.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl";
      sha256 = "0m02dsi8lvrjf4bi20ab6lm7rr6krz7pg6lzk3xjs2l9hqfjzfwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "ssh-import-id" = super.buildPythonPackage rec {
    pname = "ssh-import-id";
    version = "5.10";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/36/6e/7aaf68f975256a45fc00b237d94ce5404ffdd7e825108a1bad9218dcaf52/ssh-import-id-5.10.tar.gz";
      sha256 = "0b9djsyrqmaxncxnly6lv9k0w3d5dfzc85vnz9nbfzag1gdq2cf6";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."distro"
      self."requests"
    ];
  };
  "typing-extensions" = super.buildPythonPackage rec {
    pname = "typing-extensions";
    version = "4.2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/75/e1/932e06004039dd670c9d5e1df0cd606bf46e29a28e65d5bb28e894ea29c9/typing_extensions-4.2.0-py3-none-any.whl";
      sha256 = "020pgkh5ay36plypaksgcgmyfx58a9cc0mbxyqchs5wpw975jmv6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "update-checker" = super.buildPythonPackage rec {
    pname = "update-checker";
    version = "0.18.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0c/ba/8dd7fa5f0b1c6a8ac62f8f57f7e794160c1f86f31c6d0fb00f582372a3e4/update_checker-0.18.0-py3-none-any.whl";
      sha256 = "1zdvskjdxfnsgcxrk44iclb6haz8ixp3118dv102dzin19v69fnb";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."requests"
    ];
  };
  "urllib3" = super.buildPythonPackage rec {
    pname = "urllib3";
    version = "1.26.5";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/0c/cd/1e2ec680ec7b09846dc6e605f5a7709dfb9d7128e51a026e7154e18a234e/urllib3-1.26.5-py2.py3-none-any.whl";
      sha256 = "0z2siwabara1prpr8vbqhmcx11m6jh1y9kr6v2cqyr96vxs06fkm";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "websocket-client" = super.buildPythonPackage rec {
    pname = "websocket-client";
    version = "1.3.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/a1/9e/8ddb04ef21ea3dfe3924b884dc11fa785df662af23e049ec2d62eaba707d/websocket_client-1.3.2-py3-none-any.whl";
      sha256 = "1vyhcl9lwalpkks8znmiininqlva2i9jnbzvskhr0aqgw0difavj";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
  "yamllint" = super.buildPythonPackage rec {
    pname = "yamllint";
    version = "1.26.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fd/b8/06798c8193245017ccf6042bd6d2395ee91a2be6312c3d428cf885d60ed7/yamllint-1.26.0-py2.py3-none-any.whl";
      sha256 = "0dwn778zwcrzp1jb3h60ylk81z7jfv734wlx7sprwc295x28wpwa";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."PyYAML"
      self."pathspec"
      self."setuptools"
    ];
  };
  "yarl" = super.buildPythonPackage rec {
    pname = "yarl";
    version = "1.9.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/5f/3f/04b3c5e57844fb9c034b09c5cb6d2b43de5d64a093c30529fd233e16cf09/yarl-1.9.2.tar.gz";
      sha256 = "0w9mh8851i7chig0vab5djcxyz5p2y9zxay207c0cz2qkx5rvaq4";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."idna"
      self."multidict"
    ];
  };
  "youtube-dl" = super.buildPythonPackage rec {
    pname = "youtube-dl";
    version = "2021.12.17";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/40/93/65c208f51895f74bbfea1423974c54fff1d1c4e9a97ebee1011b021554b8/youtube_dl-2021.12.17-py2.py3-none-any.whl";
      sha256 = "0mfdg6fwdw8fqpsqy102dz3rxrbq4mqw1cs798vf0iw6wrfnsczi";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
